### PR TITLE
apply go modules

### PR DESCRIPTION
**Pull request by tomahawk28**

### CODE REVIEW

**Comment by tomahawk28** [comment]
Even the last update was 17 Aug 2016. 😆 so many situation.

**Comment by xh3b4sd** [comment]
This here looks like the last changes in this repo were made 4 years ago and `dep` did not exist or was not in use on our side at this point. 😂

**Comment by rossf7** [comment]
> 4 years ago and dep did not exist 

LOL I'm glad we're being thorough 🚀

**Comment by zeisss** [comment]
👍

**Pull request merged**
